---
title: Middlebury Styleguide
timezone: UTC
collections:
  editorial:
    title: Editorial
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
exclude:
- bower_components
- node_modules
- gulpfile.js
- package.json
- README.md
- "*.log"
markdown: kramdown
highlighter: rouge
baseurl: "/styleguide"
kramdown:
  auto_ids: true
  toc_levels: 2..6
permalink: pretty
